### ISSUE TITLE
Nie ma Mavena

### ISSUE THREAD

**Issue by LIttleAncientForestKami** [choooobert/MagicNumbers#1]
Do tego: w specce jest "showcase your skills" - czy to już jest w kodzie?

**Comment by choooobert** [comment]
Dodałem mavena :) 
showcase your skills - zmieniłem trochę kod, tak aby zawierał więcej technik programowania obiektowego. Z pewnością istnieje jeszcze wiele innych, jak na razie ciężko mi znaleźć zastosowanie ich w tym kodzie.

**Comment by LIttleAncientForestKami** [comment]
Jest lepiej. Mogłoby być jeszcze lepiej natomiast, w kontekście enkapsulacji czy abstrakcji zwłaszcza. Albo kolekcji i obsługi wyjątków. Natomiast dzięki za poprawki.
