### ISSUE TITLE
Session log

### ISSUE THREAD

**Issue by LIttleAncientForestKami** [choooobert/MagicNumbers#2]
I fed your program some files that are JPGs, PNGs and TXTs. It didn't recognize them. See log below for details.

```
[tammo@lafk-T470 src]$ java Main                                                                            [INSERT]
Give path to file : 
../../test_txt.jpg
java.lang.Exception: The file extension and inner structure of file do not correspond
 type from file structure : txt
  Type from path : undefined
	at FileExtensionAnalyzer.getFileType(FileExtensionAnalyzer.java:95)
	at Main.main(Main.java:12)
[tammo@lafk-T470 src]$ java Main                                                                            [INSERT]
Give path to file : 
../../test_png.png
../../test_png.png, fileType : undefined
[tammo@lafk-T470 src]$ java Main                                                                            [INSERT]
Give path to file : 
../../test_png.txt
../../test_png.txt, fileType : undefined
[tammo@lafk-T470 src]$ java Main                                                                            [INSERT]
Give path to file : 
../../test_jpg.txt
java.lang.Exception: The file extension and inner structure of file do not correspond
 type from file structure : jpg
  Type from path : undefined
	at FileExtensionAnalyzer.getFileType(FileExtensionAnalyzer.java:95)
	at Main.main(Main.java:12)
```

Let me know if you can correct this (and preferably the other issue too).

**Comment by choooobert** [comment]
W poleceniu było, aby program rozpoznawał gif, jpg i txt. Dodałem do programu rozpoznawanie png i rozbudowałem tak program aby łatwo można było go rozwinąć o dodatkowe dowolne rozszerzenia plików (starałem się zastosować zasadę Open/Closed principle). 

Poza tym naprawiłem buga, dzięki czemu program odczytuje poprawnie rozszerzenia ze ścieżek do plików. Wcześniej sczytywał rozszerzenia biorąc pod uwagę indeks pierwszej napotkanej kropki, zakładałem że w ścieżce takie się nie pojawią. Teraz zmieniłem i bierze pod uwagę ostatnią kropkę

**Comment by choooobert** [comment]
W poleceniu było, aby program rozpoznawał gif, jpg i txt. Dodałem do programu rozpoznawanie png i rozbudowałem tak program aby łatwo można było go rozwinąć o dodatkowe dowolne rozszerzenia plików (starałem się zastosować zasadę Open/Closed principle).

Poza tym naprawiłem buga, dzięki czemu program odczytuje poprawnie rozszerzenia ze ścieżek do plików. Wcześniej sczytywał rozszerzenia biorąc pod uwagę indeks pierwszej napotkanej kropki, zakładałem że w ścieżce takie się nie pojawią. Teraz zmieniłem i bierze pod uwagę ostatnią kropkę.

**Comment by LIttleAncientForestKami** [comment]
GIF a nie PNG - jasne, mi się pomyliło. Nowe rezultaty:

Tekst podający się za JPGa: wie, że nie JPG, nie wie, że tekst.

```
tammo@lafk-T470 magNum]$ java -jar kolejneMagiczneNumerki/target/MagicNumbers-1.0-SNAPSHOT.jar              [INSERT]
Give path to file : 
test_ASCIItxt.jpg
java.lang.Exception: Extensions detected not equal.
extension from file : undefined
extension from path : jpg
	at extensionComparator.FileExtensionStatus.getExtensionString(FileExtensionStatus.java:25)
	at extensionComparator.ExtensionComparator.main(ExtensionComparator.java:26)
```

Tekst ASCII z dziwnymi znakami końca linii: przechodzi.
```
[tammo@lafk-T470 magNum]$ java -jar kolejneMagiczneNumerki/target/MagicNumbers-1.0-SNAPSHOT.jar              [INSERT]
Give path to file : 
test_ASCIItxt_noEOL.txt
path to file : test_ASCIItxt_noEOL.txt file extension : txt
```
Prawie pusty tekst: przechodzi.
```
[tammo@lafk-T470 magNum]$ java -jar kolejneMagiczneNumerki/target/MagicNumbers-1.0-SNAPSHOT.jar              [INSERT]
Give path to file : 
test_almostEmptyTxt.txt
path to file : test_almostEmptyTxt.txt file extension : txt

Tekst ASCII: nie przechodzi. Program nie uważa, że to tekst.
```
[tammo@lafk-T470 magNum]$ java -jar kolejneMagiczneNumerki/target/MagicNumbers-1.0-SNAPSHOT.jar              [INSERT]
Give path to file : 
test_ASCIItxt.txt
java.lang.Exception: Extensions detected not equal.
extension from file : undefined
extension from path : txt
	at extensionComparator.FileExtensionStatus.getExtensionString(FileExtensionStatus.java:25)
	at extensionComparator.ExtensionComparator.main(ExtensionComparator.java:26)
```

Pusty plik podający się za JPG: uznany przez program za tekst. :o: 
```
[tammo@lafk-T470 magNum]$ java -jar kolejneMagiczneNumerki/target/MagicNumbers-1.0-SNAPSHOT.jar              [INSERT]
Give path to file : 
test_empty.jpeg
java.lang.Exception: Extensions detected not equal.
extension from file : txt
extension from path : undefined
	at extensionComparator.FileExtensionStatus.getExtensionString(FileExtensionStatus.java:25)
	at extensionComparator.ExtensionComparator.main(ExtensionComparator.java:26)
```
Gif: rozpoznany.
```
[tammo@lafk-T470 magNum]$ java -jar kolejneMagiczneNumerki/target/MagicNumbers-1.0-SNAPSHOT.jar              [INSERT]
Give path to file : 
test_gif89a.gif
path to file : test_gif89a.gif file extension : gif
```
JPG podający się za tekst: rozpoznany prawidłowo, jako obraz.
```
[tammo@lafk-T470 magNum]$ java -jar kolejneMagiczneNumerki/target/MagicNumbers-1.0-SNAPSHOT.jar              [INSERT]
Give path to file : 
test_jpg.txt
java.lang.Exception: Extensions detected not equal.
extension from file : jpg
extension from path : txt
	at extensionComparator.FileExtensionStatus.getExtensionString(FileExtensionStatus.java:25)
	at extensionComparator.ExtensionComparator.main(ExtensionComparator.java:26)
```

**Comment by choooobert** [comment]
Dodałem poprawne sprawdzanie czy plik tekstowy jest pusty. Prz sprawdzaniu czy plik jest txt, dodałem sprawdzanie wszystkich znaków ASCII, które mogą być zapisane w takim pliku.

**Comment by LIttleAncientForestKami** [comment]
OK. Zamykam.
